active_remote.gemspec
lib/active_remote/base.rb
lib/active_remote/errors.rb
lib/active_remote/persistence.rb
lib/active_remote/validations.rb
spec/lib/active_remote/dirty_spec.rb
spec/lib/active_remote/validations_spec.rb
spec/support/models/post.rb

This wires up ActiveModel::Validations to run when calling `save` and `save!`, in the same way that [active record does it](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/validations.rb).
This also includes ActiveModel::Validations::Callbacks which will add `before_validation`, `after_validation`, etc.

Add support for validations

---

spec/lib/active_remote/persistence_spec.rb

This assertation to the run_callbacks method was picking up the
validation callback, and also returning nil which cancelled the callback
chain.

Fix failing spec.

---

lib/active_remote/persistence.rb

Addresses #32 
ActiveRecord added update and update! methods to persistence, as aliases to
update_attributes and update_attributes!.  This brings ActiveRemote in
line with the interface of ActiveRecord.

Add update and update! methods

---

lib/active_remote/persistence.rb
spec/lib/active_remote/persistence_spec.rb

This adds the `update_attribute` method, to increase compatibility with the ActiveRecord interface.
http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-update_attribute

Add update_attribute method

---

lib/active_remote/dirty.rb
spec/lib/active_remote/persistence_spec.rb

The update method in the persistence module was renamed, and this
methods also needs to be renamed to overwrite the correct method.

Fix broken update functionality

---

lib/active_remote/persistence.rb

When calling `instantiate`, we see a signficant speed improvement by skipping mass-assignment protection. Since this method is intended for use with searching for remote records, skipping that protection should be fine.
// @brianstien @abrandoned

Skip mass-assignment protection when instantiating

---

lib/active_remote/attribute_defaults.rb
lib/active_remote/base.rb
spec/lib/active_remote/attribute_defaults_spec.rb
spec/support/models.rb
spec/support/models/default_author.rb

Attribute defaults were broken by the change to attribute initialization
and typecasting.
This pulls over the active_attr attribute defaults, and fixes them to
work with the way active_remote is doing attribute initialization and
typecasting.
We could probably monkeypatch this in but I thought this approach
was cleaner.  Let me know what you think.

Fix attribute defaults from active_attr

---

lib/active_remote/serialization.rb
spec/lib/active_remote/bulk_spec.rb

I ran into a case recently where I was calling `MyModel.create_all(...)` and then checking the results for `errors.present?`, but I never got errors back.
This PR adds the step of adding the remote errors whenever we are serializing remote data into `ActiveRemote` objects. This will also allow error messages to come through in `search` endpoints as well.
/cc @liveh2o @abrandoned @newellista

pass errors through on bulk rpc calls

---

lib/active_remote/association.rb
spec/lib/active_remote/association_spec.rb

We weren't defining setters during these associations before. Next steps will add a setter for has_many. I feel like that's a little different because it deals with a number of records rather than just one, so there needs to be some check that the current method does not do.
Part of #45.
@mmmries @localshred @liveh2o

Adds setters for has_one and belongs_to

---

lib/active_remote/dirty.rb

write_attribute now calls directly into attribute=, so we dont need to
do dirty tracking in both places.

No need to do dirty tracking twice

---

lib/active_remote/search.rb

Removes a deprecated method and the search callbacks feature

Remove search callbacks

---

lib/active_remote/attribute_definition.rb
lib/active_remote/base.rb
lib/active_remote/persistence.rb
lib/active_remote/rpc.rb
lib/active_remote/typecasting.rb
spec/lib/active_remote/rpc_spec.rb

This improves the performance of the handoff from rpc response to creating a new object.  There are some significant time savings by bypassing all of the setters.
This will set the attributes hash directly when we get a response from rpc, bypassing the setters but still doing type casting.

Init from rpc

---

lib/active_remote/association.rb
spec/lib/active_remote/association_spec.rb

This also adds a check to see if the new value in the setter is an array because duh.
Part of https://github.com/liveh2o/active_remote/issues/45
@liveh2o

Adds writer method for has_many associations

---

lib/active_remote/errors.rb
lib/active_remote/rpc_adapters/protobuf_adapter.rb

From https://github.com/liveh2o/active_remote/issues/39
Example set of errors https://github.com/ruby-protobuf/protobuf/blob/master/lib/protobuf/rpc/error/client_error.rb
This will make it so we bubble up the type of error given from Protobuf
@liveh2o @abrandoned @mmmries

Add granular protobuf errors for ActiveRemote

---

lib/active_remote/rpc_adapters/protobuf_adapter.rb

Not all errors returned here will have an error_type method.  In some
cases these errors are just structs.

Guard against undefined method errors

---

lib/active_remote/persistence.rb
spec/lib/active_remote/persistence_spec.rb

ActiveRecord allows the primary key to be set on create. This makes
ActiveRemote#create behave the same way by allowing the primary_key
attribute to be sent in a create operation.
@liveh2o

Allow primary_key to be set on create

---

lib/active_remote/typecasting/date_time_typecaster.rb
spec/lib/active_remote/typecasting_spec.rb

The Date typecaster will gracefully handle invalid dates, but DateTime
does not. This changes the behavior of DateTime types to match the
behavior of Date types.

Handle invalid DateTime attributes gracefully

---

lib/active_remote/attribute_definition.rb
lib/active_remote/serializers/protobuf.rb
lib/active_remote/type.rb
lib/active_remote/type/registry.rb
spec/support/models/typecasted_author.rb

In preparation for transitioning to Active Model 5.2, add support for registering types that can be used to define attributes without using the existing `:type` or `:typecaster` options:
```ruby
attribute :name, :string
```
The `:type` and `:typecaster` options still work, but this brings the interface for the attribute method inline with what it is in Active Model 5.2.
Additionally, update the Protobuf serializer to use the new type registry rather than maintaining a map of typecasters directly.

Add support for registering types

---

lib/active_remote/serializers/protobuf.rb
spec/lib/active_remote/serializers/protobuf_spec.rb
spec/support/definitions/serializer.proto
spec/support/protobuf/serializer.pb.rb

Previously, the Protobuf serializer would gracefully handle values that had no explicit typecaster. That unexpectedly changed with the latest release, resulting an in an unknown type error being thrown for Protobuf fields without explicit corresponding Ruby types (i.e., enums, messages).
Update the Protobuf serializer to restore the previous behavior, along with specs to ensure it doesn't happen again.

Fix unknown type error in Protobuf serializer

---

lib/active_remote/query_attributes.rb
spec/lib/active_remote/query_attribute_spec.rb

Active Record considers numeric values present only when `zero?` is false. This is incompatible with Protobuf enums since they are usually zero-based, but will also cause numeric values not to be sent over the wire when they are 0, 0.0, etc. This may be fine for AR, but doesn't work so well here in Active Remote.

Make query attributes more permissive

---

lib/active_remote/persistence.rb
lib/active_remote/rpc.rb
spec/lib/active_remote/persistence_spec.rb
spec/lib/active_remote/rpc_spec.rb

Add a #remote method that executes a remote call on the current object and updates its attributes and errors from the response.
- Defaults request args to the scope key hash (e.g., guid: 'ABC-123') when none are given
- Returns false if the response contained errors; otherwise, returns true
This makes it much simpler to perform custom RPC actions that modify the remote record.
// @newellista

Add ability to execute remote calls on current object

---

lib/active_remote/errors.rb
lib/active_remote/persistence.rb
spec/lib/active_remote/errors_spec.rb
spec/lib/active_remote/persistence_spec.rb

This seems like a more correct behavior than: `ActiveRemote::RemoteRecordNotSaved: ActiveRemote::RemoteRecordNotSaved`.
cc @liveh2o

Include response errors in RemoteRecordNotSaved exception

---

active_remote.gemspec
lib/active_remote/primary_key.rb
spec/lib/active_remote/primary_key_spec.rb

Resolves https://github.com/liveh2o/active_remote/issues/79
ActiveModel first checks to make sure that the primary key field responds to messages (see https://github.com/rails/rails/blob/5-2-stable/activemodel/lib/active_model/conversion.rb#L60), the same should probably happen here.

check for existence of primary key is to_key

---

lib/active_remote/attribute_methods.rb

In order to be able to override `_write_attribute` we should not duplicate the logic but call the existing logic.

revert the reader and writer methods so they can be overidden

---

.github/workflows/ruby.yml
lib/active_remote/association.rb
spec/lib/active_remote/persistence_spec.rb

Specs work on:
Jruby 9.3/9.4
CRuby 2.7/3.0/3.1
after the arguments change.

added ruby-3.1 compatibility

---

.travis.yml
lib/active_remote/search.rb
spec/lib/active_remote/search_spec.rb

Currently we have `.search`, which returns a (possibly empty) array of results, and we have `.find`, which returns a single result or raises `ActiveRemote::RemoteRecordNotFound`. 
We see a common pattern when we know we need only one record, but we want `nil` instead of raising an error:
```
RemoteModel.search(:key => value).first
```
This MR proposes adding a `.find_by` method to ActiveRemote classes, which would allow us to instead write:
```
RemoteModel.find_by(:key => value)
```
The new method would be parallel to the ActiveRecord `.find_by` method.

Add `find_by` to the Search module

---

.github/workflows/main.yml
README.md

Update the CI workflow to run against `main` now that the default branch has been renamed, and add a status badge to the README.

Add workflow status badge for main

---

lib/active_remote/base.rb
lib/active_remote/dirty.rb

Do not skip dirty tracking when initializing to match Rails behavior. Instead, use .instantiate, or manually reset changes as needed.

Match Rails dirty tracking behavior
